# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ThirdPartyControls' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'KDCircularProgress'
  pod 'HGCircularSlider', '~> 2.0.0'
  pod 'NVActivityIndicatorView'
  pod 'SSSpinnerButton'
  pod 'RAMAnimatedTabBarController'
  pod 'MinimalTabBar'
  pod 'JTAppleCalendar', '~> 7.0'
  pod 'FaceAware'
  pod 'Kingfisher' #, '3.2.1'
  pod 'paper-onboarding'
  pod 'PullToMakeSoup', '~> 2.0'
  



  # Pods for ThirdPartyControls

end
